apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: registry
      labels:
        app: registry
    spec:
      ports:
        - port: 8080
          targetPort: 8080
          name: client
      selector:
        app: registry
  - apiVersion: "apps.openshift.io/v1"
    kind: "DeploymentConfig"
    metadata:
      name: registry
    spec:
      replicas: 1
      selector:
        app: registry
      template:
        metadata:
          labels:
            app: registry
        spec:
          containers:
            - name: kafka-registry
              image: apicurio/apicurio-registry-mem:1.3.1.Final
              env:
                - name: QUARKUS_PROFILE
                  value: "prod"
                - name: APPLICATION_ID
                  value: "registry_id"
                - name: KAFKA_BOOTSTRAP_SERVERS
                  value: "${KAFKA_BOOTSTRAP_URL}"
                - name: APPLICATION_SERVER
                  value: "localhost:9000"
              ports:
                - containerPort: 8080
                  name: client
          restartPolicy: Always
      triggers:
      - type: "ConfigChange"
kind: List
metadata: {}